### ISSUE TITLE
I don't quite understand what the mistake is. Error loading script: posex.py

### ISSUE THREAD

**Issue by Apulaz** [hnmr293/posex#9]
`Error loading script: posex.py
Traceback (most recent call last):
  File "C:\Users\123123123\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\123123123\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\123123123\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\posex\scripts\posex.py", line 14, in <module>
    posex.set_save_dir(os.path.join(os.path.dirname(__file__), '..', 'saved_poses'))
NameError: name '__file__' is not defined`

All the data is in the log, why doesn't it work on my machine?

**Comment by hnmr293** [comment]
thank you for your feedback.
I need information for reproducing the issue. You use google colab, right?

**Comment by hnmr293** [comment]
I've tried to fix it. Please try again.
If you get same error, please reopen this issue.

**Comment by Apulaz** [comment]
`Error calling: C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\posex\scripts\posex.py/ui
Traceback (most recent call last):
  File "C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 232, in wrap_call
    res = func(*args, **kwargs)
  File "C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\posex\scripts\posex.py", line 33, in ui
    ext = get_self_extension()
  File "C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\posex\scripts\posex.py", line 115, in get_self_extension
    if ext.path in __file__:
NameError: name '__file__' is not defined

Error calling: C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\posex\scripts\posex.py/ui
Traceback (most recent call last):
  File "C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 232, in wrap_call
    res = func(*args, **kwargs)
  File "C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\posex\scripts\posex.py", line 33, in ui
    ext = get_self_extension()
  File "C:\Users\dimap\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\posex\scripts\posex.py", line 115, in get_self_extension
    if ext.path in __file__:
NameError: name '__file__' is not defined`

**Comment by hnmr293** [comment]
oh, sorry!
I've fixed it again. how about this time?

**Comment by Apulaz** [comment]
Thank you, the tab appeared
